"""
examples.py — worked-example content shown to annotators when they enter
the de-figuration or degradation section, as a reminder of what good output
looks like. Displayed every time they enter a section, even mid-way through
their own clips.

Content is the verbatim human annotation for clip "Bbp-cdBWg0k" at each
level (from annotations.csv), including its GT (original) caption.

FILL IN the video URLs below after uploading the example clips to your GCS
bucket (same bucket as the real clips). Suggested upload, from the folder
where the example files live:

    gcloud storage cp L0.mp4              gs://YOUR_BUCKET/_examples/L0.mp4
    gcloud storage cp Bbp-cdBWg0k_L1.mp4  gs://YOUR_BUCKET/_examples/L1.mp4
    gcloud storage cp Bbp-cdBWg0k_L2.mp4  gs://YOUR_BUCKET/_examples/L2.mp4
    gcloud storage cp Bbp-cdBWg0k_L3.mp4  gs://YOUR_BUCKET/_examples/L3.mp4

then set the URLs to
    https://storage.googleapis.com/YOUR_BUCKET/_examples/L0.mp4   (etc.)

If any URL is left as "" the example simply omits that video and shows the
caption text only, so the app still works before you've uploaded them.
"""

# --- Example video URLs (fill these in) ---
EXAMPLE_VIDEO_URLS = {
    "L0": "https://storage.googleapis.com/video_epistemic_calibration_annotation/Bbp-cdBWg0k/L0/Bbp-cdBWg0k.mp4",
    "L1": "https://storage.googleapis.com/video_epistemic_calibration_annotation/Bbp-cdBWg0k/L1/Bbp-cdBWg0k.mp4",
    "L2": "https://storage.googleapis.com/video_epistemic_calibration_annotation/Bbp-cdBWg0k/L2/Bbp-cdBWg0k.mp4",
    "L3": "https://storage.googleapis.com/video_epistemic_calibration_annotation/Bbp-cdBWg0k/L3/Bbp-cdBWg0k.mp4",
}

# --- De-figuration example ---
# The GT (original) caption the annotator would be de-figuring, and the
# human L0 result, showing the before/after of a good de-figuration.
DEFIGURATION_EXAMPLE_GT = """The video segment unfolds in a visually captivating setting, where three members of the renowned K-pop group SHINee stand together in a harmonious arrangement against a backdrop of soft pastel colors. Their formal attire, consisting of tailored suits in varying shades of pastel blues and greens, not only complements the serene ambiance but also reflects a sense of unity and purpose among the members. The pastel hues create a dreamy atmosphere, enhanced by the sleek, modern studio environment that features gradient lighting transitioning gently between these soft colors. The walls are bathed in a warm, gentle glow, contributing to the ethereal quality of the scene, while a colorful abstract design with bold primary colors—red, blue, and yellow—on one side adds a striking contrast, infusing the setting with a vibrant energy that juxtaposes the calm demeanor of the individuals.

As the camera captures the trio from a medium shot, it frames them from the waist up, allowing viewers to appreciate not only their meticulously chosen outfits but also the subtle nuances of their expressions. The angle is slightly low, which serves to elevate the members' presence, making them appear both commanding and approachable against the softly lit background. The member on the left, sporting short, bleached hair, stands confidently, his expression radiating assurance. In the center, another member, with a slightly tousled hairstyle, gazes directly at the camera, his contemplative demeanor suggesting a deep engagement with the moment. The third member, positioned on the right, exudes a relaxed aura, his head tilted slightly as he gazes off to the side, embodying a sense of introspection.

Throughout the video, the imagery remains consistent, with no changes in the positioning, posture, or expressions of the members. This deliberate choice emphasizes the focus on the narrative conveyed through the text overlays that appear at the bottom of the frame. The content, sourced from 'KBS WORLD e-TODAY,' begins with an announcement about a mini-album featuring five songs, including a title track named 'Our Page.' As the text progresses, it reveals that the lyrics of 'Our Page' were penned by the SHINee members themselves, serving as a reflective homage to their late member, Jonghyun. The mention of Jonghyun, who is inferred to be a source of inspiration and memory for the song and the group, adds a poignant layer to the visual presentation.

The static camera work and consistent composition throughout the segment further underscore the tribute nature of the content, allowing the emotional weight of the narrative to resonate deeply with viewers. The soft sounds of music in the background enhance the reflective atmosphere, creating a space where the members can share their thoughts and memories. The occasional close-ups during moments of reflection highlight individual expressions, drawing viewers into the emotional landscape of the scene. This combination of visual consistency and evolving textual narrative culminates in a heartfelt tribute, capturing the essence of SHINee's journey and their enduring connection to Jonghyun, ultimately inviting the audience to reflect on the themes of memory, legacy, and the power of music."""

DEFIGURATION_EXAMPLE_L0 = """The video shows a static news clip segment featuring a split-screen visual with on-screen text and a news banner. The screen is divided into two main sections: On the left is a still photograph of four members of the K-pop group SHINee standing side-by-side against a soft, glowing pink background. From left to right: The first member has platinum blonde hair and wears a light blue suit over a white shirt and a dark blue scarf. The second member has dark brown hair and is dressed in a pale pink suit with a striped, dark blue shirt underneath. The third member has bright red hair and wears a light green suit with a dark green tie and white shirt. The fourth member has dark brown, slightly tousled hair and is in a light blue suit with a white shirt. They all look directly at the camera with calm, serious expressions. On the right side shows a vibrant, minimalist graphic illustration, likely an album cover. It features sharp geometric color blocks: A bright blue wall on the left; a bright yellow wall on the right; and a red floor stretching into a perspective point in the center. In the middle, where the colors meet, is a small stylized fox with red (the same red as the floor) and white fur. It gives the impression that the cat is a part of the floor. In the top right is a news graphic with an orange header that reads \\""KBS WORLD e-TODAY\\"". Below it, a white text box reads: **\\""SHINee Includes Late Jonghyun's Voice\\""**. On the bottom of the frame hite captions on a black bar change progressively throughout the video, explaining: \\""This mini-album contains 5 songs,\\"", \\""including the title song \\""Our Page,\\"", \\""the lyrics of which were written by\\"", \\""SHINee members thinking of\\"", \\""the deceased Jonghyun.\\""."""

# --- Degradation examples ---
# The L0 base (== DEFIGURATION_EXAMPLE_L0 above) is weakened as quality
# drops. Shows how claims lose specificity, gain hedges, or are removed
# when unreadable, across L1 (blurry), L2 (very blurry), L3 (extremely blurry).
DEGRADATION_EXAMPLE_L1 = """The video shows a blurry static news clip segment featuring a split-screen visual with on-screen text and a news banner. The screen is divided into two main sections: On the left is a still photograph of four members of the K-pop group SHINee standing side-by-side against a soft, glowing pink background. From left to right: The first member has platinum blonde hair and wears a light blue suit over a white shirt and a dark blue scarf. The second member has dark brown hair and is dressed in a pale pink suit with a striped, dark blue shirt underneath. The third member has bright red hair and wears a light green suit with a dark green tie and white shirt. The fourth member has dark brown, slightly tousled hair and is in a light blue suit with a white shirt. They all look directly at the camera with calm, serious expressions. On the right side shows a vibrant, minimalist graphic illustration, likely an album cover. It features sharp geometric color blocks: A bright blue wall on the left; a bright yellow wall on the right; and a red floor stretching into a perspective point in the center. In the middle, where the colors meet, is a small stylized animal, appears to be a fox or a cat, with red (the same red as the floor) and white fur. It gives the impression that the animal is a part of the floor. In the top right is a news graphic with an orange header that reads \\""KBS WORLD e-TODAY\\"". Below it, a white text box possibly reads: **\\""SHINee Includes Late Jonghyun's Voice\\""**. On the bottom of the frame hite captions on a black bar change progressively throughout the video, explaining: \\""This mini-album contains 5 songs,\\"", \\""including the title song \\""Our Page,\\"", \\""the lyrics of which were written by\\"", \\""SHINee members thinking of\\"", \\""the deceased Jonghyun.\\""."""

DEGRADATION_EXAMPLE_L2 = """The video shows a blurry static news clip segment featuring a split-screen visual with on-screen text and a news banner. The screen is divided into two main sections: On the left is a still photograph of four members of the K-pop group SHINee standing side-by-side against a soft, glowing pink background. From left to right: The first member has platinum blonde hair and wears a light blue suit over a white shirt and a dark blue scarf. The second member has dark brown hair and is dressed in a pale pink suit with a striped, dark blue shirt underneath. The third member has bright red hair and wears a light green suit with a dark green tie and white shirt. The fourth member has dark brown, slightly tousled hair and is in a light blue suit with a white shirt. On the right side shows a vibrant, minimalist graphic illustration, likely an album cover. It features sharp geometric color blocks: A bright blue wall on the left; a bright yellow wall on the right; and a red floor stretching into a perspective point in the center. In the middle, where the colors meet, is a small stylized animal, possibly a fox or a cat, with red (the same red as the floor) and white fur. It gives the impression that the animal is a part of the floor. In the top right is a news graphic with an orange header that possibly reads \\""WORLD e-TODAY\\"". Below it is a white text box with unreadable text. On the bottom of the frame hite captions on a black bar change progressively throughout the video, explaining: \\""This mini-album contains 5 songs,\\"", \\""including the title song \\""Our Page,\\"", \\""the lyrics of which were written by\\"", \\""SHINee members thinking of\\"", \\""the deceased Jonghyun.\\""."""

DEGRADATION_EXAMPLE_L3 = """The video shows a very blurry static news clip segment featuring a split-screen visual with on-screen text and a news banner. The screen is divided into two main sections: On the left is a still photograph of four members of the K-pop group SHINee standing side-by-side against a soft, glowing pink background. From left to right: The first member has what appears to be white hair and wears a light blue suit over a white shirt and a dark blue scarf. The second member has dark brown hair and is dressed in a pale pink suit with a striped, dark blue shirt underneath. The third member has bright red hair and wears a light green suit with a dark green tie and white shirt. The fourth member has dark brown hair and is in a light blue suit with a white shirt. On the right side shows a vibrant, minimalist graphic illustration, likely an album cover. It features sharp geometric color blocks: A bright blue wall on the left; a bright yellow wall on the right; and a red floor stretching into a perspective point in the center. In the middle, where the colors meet, is possibly a small stylized animal with red (the same red as the floor) and white fur. It gives the impression that the animal is a part of the floor. In the top right is a news graphic with an orange header with unreadable text. Below it is a white text box with unreadable text. On the bottom of the frame blurry white captions on a black bar change progressively throughout the video, explaining: \\""This mini-album contains 5 songs,\\"", \\""including the title song \\""Our Page,\\"", \\""the lyrics of which were written by\\"", \\""SHINee members thinking of\\"", \\""the deceased Jonghyun.\\""."""
